const handler = {
  title: 'Space Invaders',
  enemyRowAmount: 8,
  enemyColumnAmount: 4,
  enemyHorizontalSpacing: 2,
  enemyVerticalSpacing: 1,
  playerStartingPositionX: 30,
  playerStartingPositionY: 35,
  screenWidth: 70,
  screenHeight: 40,
  ticks: 50,
  bulletCooldown: 500,
  scoreMultiplier: 15,
  speedMultiplierPerLevel: 1.1,
  leftKeyPress: ['a', 'A', 'left'],
  rightKeyPress: ['d', 'D', 'right'],
  pauseButtons: ['p', 'P'],
  exitButtons: ['C-c'],
  shootKeyPress: ['space'],
  player: {
    width: 3,
    height: 2,
    color: 'red',
  },
  enemy: {
    width: 3,
    height: 2,
    color: 'red',
  },
  bullet: {
    width: 1,
    height: 1,
    color: 'red',
  },
  dashboardX: 70,
  dashboardY: 0,
  dashboardWidth: 50,
  dashboardHeight: 40,
};

module.exports = handler;
